### ISSUE TITLE
tracking issue: Swtich a scheme based config

### ISSUE THREAD

**Issue by pascalkuthe** [helix-editor/helix#10389]
We have settled on a scheme (likely steel see #8675) based plugin system. One of the primary goals of the plugin systems is not just allowing user to write plugins for functionality that isn't suited for integration in core but also to allow a more flexible, scriptable and extensible config that will replace that config.

This issue is not meant to discuss the choice of scheme, please keep such discussion out of this issue.

There are many open issues that we want to address with a scheme based config. We generally don't want to invest more time into significant additions to the toml config so I will be closing these issue in favor of this one To make easier to track I decided to centralize these issues here. Once an initial prototype lands we can split out issues fro unadressed features again but right now that we don't even have a prototype that just isn't producitve. I tried to give a rough summery of how I hope to adress these things but these aren't in depth proposals/fully developed ideas yet.

* #1513, #1498 and https://github.com/helix-editor/helix/issues/5734: allow defining/reusing keymap bindings (both grouping and sequences): Will be automatically handled by making keybindings first class values (that can be stored in variables). This will include the builtin minor modes 
* https://github.com/helix-editor/helix/issues/6896 and #3702: keep the current behaviour of overwriting (since its imo the right thing to do) and add a function that automatically merges instead
* any breaking changes we may want to make to the config should be done during the migration as we are breaking users configs anyway

Work items:

* [ ] revamp the config system so its flexible enough for a scritable config and not inherently tied to serde/toml anymore (#8853 / #9318). This will remomve most of the current based toml/serde based system and only leave a compatability layer in place
* [ ] add scheme support to helix (#8675)
* [ ] implement ergonomic declarative config in scheme
* [ ] remove toml compatibility layer

**Comment by SoraTenshi** [comment]
I just also want to add to this:
Since a lot of Users are Nix users, it'd be a shame to see the nice declarative approach of nix to be gone (not sure if this has been thought of yet)
But a nice abstraction layer as it is currently in the flake definition seems to be a very important option (imo)

**Comment by pascalkuthe** [comment]
the nix config can generate a scheme config file. This likely won't cover the full customizability of a scriptable config but it wouldn't be much worse than what we have today. It's not practical to support nix as a first class configuration/scipting language since its not made for that and we can't tie helix to a specific package manager.

**Comment by SoraTenshi** [comment]
> This likely won't cover the full customizability of a scriptable config but it wouldn't be much worse than what we have today. 
That's basically all I asked for.
As a first class citizen it was never in my mind but I am happy as it currently is. :)

**Comment by clarfonthey** [comment]
Just commenting here as #5046 was closed: I think that it is still a good idea to have some form of direct key-to-key remapping in addition to being able to configure all the keybindings. Sure, proper schemes for remappings of common layouts like Dvorak, AZERY, and QWERTZ will probably be added, but less-common layouts like Bépo might be missed, and I think it's still generally a good feature to have.

To me, the most natural way to use keybindings on a different keyboard layout is… to just use them, irrelevant of what the underlying keys are. Sure, the mnemonics will be messed up, but it's better than shuffling them around to the point where your fingers get tied up. Insertion mode is a separate mode entirely so it doesn't need to worry about those bindings; you can just use the native symbols from the layout.

**Comment by pascalkuthe** [comment]
I don't intend to continue the long discussion that was there already on this here so I will mark further comments regarding this as off topic. 

But no we will not add this to core. One of the motivations for adding scheme based configs is that we don't have to continuously bloat core with new features and instead offer a more flexible config that will users to add what they need themselves.

Particularly the scheme config should be flexible enough that you can easily implement almost exactly the same thing as https://github.com/helix-editor/helix/pull/5046 in your config/as a plugin. Essentially you would be iterating the current keymap, doing a replacement from one "layout" to another and build a new keymap with the mapped bindings.

**Comment by clarfonthey** [comment]
Oh, I really should have read more into what exactly this was proposing better. That seems perfectly reasonable then; as long as this is easily doable with the new system, I have no complaints.

**Comment by AndreiSva** [comment]
I would love this

**Comment by gyreas** [comment]
I'm curious, how easy is it to (de)serialise scheme compared to toml?

**Comment by pascalkuthe** [comment]
> I'm curious, how easy is it to (de)serialise scheme compared to toml?

Its not a dataformat it's a programming language so there is not deserialization. You execute code in an interpreter and we habe an API to set config options

**Comment by gyreas** [comment]
...and lisps are known for being able to double as both dataformat and proglang.

I'm looking forward to this.

**Comment by gyreas** [comment]
Btw, there's still a typo in the title

**Comment by CaesarXInsanium** [comment]
I think it's funny that there's typos here.

**Comment by omentic** [comment]
> This issue is not meant to discuss the choice of scheme, please keep such discussion out of this issue.

Where is such discussion intended to occur? I'm a little lost on what the benefits of switching from TOML to Scheme would be. Is there additional context to this issue?

**Comment by AndreiSva** [comment]
> > This issue is not meant to discuss the choice of scheme, please keep such discussion out of this issue.
> 
> Where is such discussion intended to occur? I'm a little lost on what the benefits of switching from TOML to Scheme would be. Is there additional context I'm missing?

Personally I think using scheme for the configuration would allow for much more expressive / powerful configurations. For example you can have real control flow, macros, etc instead of purely declarative TOML. Also, it has the potential to be much more consistent and elegant with the upcoming scheme-based plugin system.

**Comment by omentic** [comment]
Ah, that seems to be the context I'm missing.

**Comment by zmc** [comment]
I understand the motivation behind adding programmatic configuration, but I'm curious: is it truly necessary to drop TOML as a config format? I'm not here to argue against adding scheme support, though I _really_ don't want to have to learn it myself. And there are some valid reasons to avoid executable config files.

**Comment by ireina7** [comment]
> I understand the motivation behind adding programmatic configuration, but I'm curious: is it truly necessary to drop TOML as a config format? I'm not here to argue against adding scheme support, though I _really_ don't want to have to learn it myself. And there are some valid reasons to avoid executable config files.

Agree. I think many users (just like me) just want simple configs as toml format. If we want to add some new kind of scheme, we can still keep toml compatible. I like toml and helix's simplicity and DO NOT want helix to be complex and giant.

**Comment by alexeymuranov** [comment]
> I understand the motivation behind adding programmatic configuration, but I'm curious: is it truly necessary to drop TOML as a config format? I'm not here to argue against adding scheme support, though I _really_ don't want to have to learn it myself. And there are some valid reasons to avoid executable config files.

Maybe it would be good enough to provide a simple Scheme function that loads config from a toml file?

**Comment by NikitaRevenco** [comment]
Would like to mention a comment from https://github.com/helix-editor/helix/issues/8853 here

> Some suggestions:
> - When a part of the config is invalid, just that option should be disabled and not the entire config (see https://github.com/helix-editor/helix/discussions/12342)
> - Helix should ship with a config migration tool when this change happens. E.g. `hx migrate-config` which will transform the toml config into a steel one

**Comment by peterdelevoryas** [comment]
Does it have to be Scheme? (Was there a discussion on selecting Scheme in particular?)

**Comment by nik-rev** [comment]
> any breaking changes we may want to make to the config should be done during the migration as we are breaking users configs anyway

One thing I think we could do is rename all themes to be `kebab-case`. This was previously attempted in #12201 but was decided against because it would break users configs

**Comment by djmattyg007** [comment]
One of the things that really appealed to me when I discovered Helix is the fact that its configuration syntax isn't turing-complete. I don't want to spend oodles of time learning new programming languages just to configure my editor. I want something that, for the most part, just works out of the box with absolute minimal configuration. I'd be very sad if the current TOML-based configuration was abandoned.

**Comment by nasxisbest** [comment]
Yea lmao just use some LazyVim for dat, Helix is designed to be simple
