### ISSUE TITLE
Tracking issue for popup

### ISSUE THREAD

**Issue by ath3** [helix-editor/helix#10569]
- [ ] panic when resizing (pr #10507)

- [ ] hidden popup items with borders enabled (issue #10553) (pr #10566)

- [ ] popup too small to fit below (pr #10566)

![popup_below_before_border](https://github.com/helix-editor/helix/assets/45574139/056622d6-c006-4160-bbdf-bc403ad477da)

- [ ] scroll tracks in wrong place after pushing key down multiple times, when the space is small and the menu opens above
![menu_scroll_track](https://github.com/helix-editor/helix/assets/45574139/878f3b8e-7ba7-4a61-93b2-874e07bd0ab0)

- [ ] panic after pressing the down key on the last visible item, if the menu is opened below and has more items than what is visible
![seven_items](https://github.com/helix-editor/helix/assets/45574139/cbbac433-8c86-4fff-a977-ac4b221db229)

**Comment by gyreas** [comment]
pop up not disappearing on mouse action such as click

**Comment by pascalkuthe** [comment]
That is not a new regression I think that's just how they always worked so that's not relevant to this issue

**Comment by gyreas** [comment]
Alright then. It's a small inconsistency but not an annoyance.
